import { db } from "@workspace/db";
import { agentsTable, propertiesTable } from "@workspace/db";

const agents = [
  {
    name: "Rajesh Patel",
    email: "rajesh.patel@estatevista.com",
    phone: "+91 98250 11001",
    photo: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop",
    title: "Senior Property Consultant",
    bio: "15 years of experience in Ahmedabad real estate. Specialist in premium residential and commercial properties across Satellite, Bodakdev and SG Highway corridor.",
    rating: 4.9,
    totalSales: 310,
    activeListings: 22,
    specializations: ["Luxury Residential", "Commercial", "Investment Properties"],
    languages: ["Gujarati", "Hindi", "English"],
    yearsExperience: 15,
  },
  {
    name: "Priya Mehta",
    email: "priya.mehta@estatevista.com",
    phone: "+91 98790 22002",
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop",
    title: "Residential Properties Expert",
    bio: "Trusted advisor for families looking for 2BHK–4BHK homes across Bopal, Thaltej, and New Ranip. Known for her patient approach and deep knowledge of Ahmedabad's western suburbs.",
    rating: 4.8,
    totalSales: 275,
    activeListings: 18,
    specializations: ["Residential", "New Developments", "Family Homes"],
    languages: ["Gujarati", "Hindi", "English"],
    yearsExperience: 10,
  },
  {
    name: "Amit Shah",
    email: "amit.shah@estatevista.com",
    phone: "+91 99090 33003",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
    title: "Commercial Real Estate Specialist",
    bio: "Expert in commercial office spaces, retail shops and showrooms on CG Road, SG Highway and GIFT City. Over 8 years closing high-value deals for businesses and startups.",
    rating: 4.7,
    totalSales: 198,
    activeListings: 26,
    specializations: ["Commercial", "Office Spaces", "Retail"],
    languages: ["Gujarati", "Hindi", "English"],
    yearsExperience: 8,
  },
  {
    name: "Neha Desai",
    email: "neha.desai@estatevista.com",
    phone: "+91 98250 44004",
    photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop",
    title: "Luxury Homes Advisor",
    bio: "Specialises in ultra-premium bungalows, penthouses, and gated community villas across Vastrapur, Shilaj Road, and Judges Bungalow Road. Personal shopper for HNI clients.",
    rating: 4.95,
    totalSales: 142,
    activeListings: 9,
    specializations: ["Luxury", "Bungalows", "Penthouses"],
    languages: ["Gujarati", "Hindi", "English"],
    yearsExperience: 12,
  },
  {
    name: "Vikram Joshi",
    email: "vikram.joshi@estatevista.com",
    phone: "+91 97370 55005",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop",
    title: "Industrial & Plots Expert",
    bio: "Deep expertise in industrial sheds, warehouses and GIDC plots across Naroda, Vatva, Odhav, and Changodar. Connects manufacturers and logistics companies with the right infrastructure.",
    rating: 4.6,
    totalSales: 167,
    activeListings: 31,
    specializations: ["Industrial", "Plots", "Warehouses", "GIDC"],
    languages: ["Gujarati", "Hindi"],
    yearsExperience: 9,
  },
  {
    name: "Kavita Agarwal",
    email: "kavita.agarwal@estatevista.com",
    phone: "+91 98790 66006",
    photo: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop",
    title: "Investment Property Advisor",
    bio: "Data-driven approach to real estate investment. Helps clients build rental portfolios and identify high-yield plots near upcoming infrastructure projects like the Metro and Ring Road.",
    rating: 4.7,
    totalSales: 224,
    activeListings: 20,
    specializations: ["Investment", "Rental Yield", "Plots", "Multi-family"],
    languages: ["Gujarati", "Hindi", "English"],
    yearsExperience: 11,
  },
];

// Prices in INR (rupees)
// 1 Lakh = 100,000 | 1 Crore = 10,000,000
const properties = [
  // ─── RESIDENTIAL ──────────────────────────────────────────────────────────
  {
    title: "4BHK Premium Villa with Private Pool — Bodakdev",
    description: "Stunning 4BHK independent villa on a prime Bodakdev plot with private swimming pool, landscaped garden, and modular kitchen. Premium Italian marble flooring, 3-car garage, and smart home automation throughout.",
    type: "residential",
    subtype: "Villa",
    status: "for_sale",
    price: 45000000, // ₹4.5 Cr
    pricePerSqft: 12000,
    address: "12, Judges Bungalow Road, Bodakdev",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380054",
    lat: 23.0500,
    lng: 72.5100,
    area: 3750,
    bedrooms: 4,
    bathrooms: 4,
    yearBuilt: 2021,
    parking: 3,
    floors: 2,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80",
    ],
    amenities: ["Private Pool", "Smart Home", "3-Car Garage", "Modular Kitchen", "Italian Marble", "Landscaped Garden", "CCTV Security"],
    views: 4823,
    agentIndex: 3,
  },
  {
    title: "3BHK Luxury Apartment — Vastrapur Lake View",
    description: "Exquisite 3BHK apartment with unobstructed lake views in Vastrapur. Floor-to-ceiling windows, imported wooden flooring, and a rooftop clubhouse with city panorama. Walking distance from Vastrapur Lake garden.",
    type: "residential",
    subtype: "Apartment",
    status: "for_sale",
    price: 18500000, // ₹1.85 Cr
    pricePerSqft: 9500,
    address: "Aurora Skyline, Vastrapur",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380015",
    lat: 23.0427,
    lng: 72.5282,
    area: 1948,
    bedrooms: 3,
    bathrooms: 3,
    yearBuilt: 2022,
    parking: 2,
    floors: 14,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa12c98?w=1200&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80",
    ],
    amenities: ["Lake View", "Rooftop Clubhouse", "Swimming Pool", "Gym", "Intercom", "24hr Security", "Reserved Parking"],
    views: 3891,
    agentIndex: 0,
  },
  {
    title: "Penthouse — Prahlad Nagar Corporate Road",
    description: "Sky-high penthouse on the 24th floor with a private terrace and panoramic views of the Satellite skyline. Double-height living room, premium fixtures, and exclusive concierge services.",
    type: "residential",
    subtype: "Penthouse",
    status: "for_sale",
    price: 65000000, // ₹6.5 Cr
    pricePerSqft: 18000,
    address: "Pinnacle Heights, Prahlad Nagar",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380015",
    lat: 23.0250,
    lng: 72.5082,
    area: 3611,
    bedrooms: 4,
    bathrooms: 5,
    yearBuilt: 2023,
    parking: 3,
    floors: 24,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80",
    ],
    amenities: ["Private Terrace", "Concierge", "Smart Automation", "Wine Cellar", "Private Gym", "Sky Lounge"],
    views: 5210,
    agentIndex: 3,
  },
  {
    title: "2BHK Ready-to-Move Apartment — Bopal",
    description: "Spacious 2BHK in a gated community near Bopal Chokdi. Vastu-compliant layout, covered parking, children's play area, and 24×7 water supply. Ideal for young families.",
    type: "residential",
    subtype: "Apartment",
    status: "for_sale",
    price: 6500000, // ₹65 L
    pricePerSqft: 5200,
    address: "Shivalik Residency, Bopal",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380058",
    lat: 23.0080,
    lng: 72.4750,
    area: 1250,
    bedrooms: 2,
    bathrooms: 2,
    yearBuilt: 2020,
    parking: 1,
    floors: 6,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80",
    ],
    amenities: ["Gated Community", "Children Play Area", "Covered Parking", "24hr Water", "CCTV", "Garden"],
    views: 2140,
    agentIndex: 1,
  },
  {
    title: "3BHK Semi-Furnished Flat — Satellite",
    description: "Well-planned 3BHK in the heart of Satellite with modular kitchen already installed. Prime location — 5 min from SG Highway, close to malls, schools and hospitals.",
    type: "residential",
    subtype: "Apartment",
    status: "for_sale",
    price: 14000000, // ₹1.4 Cr
    pricePerSqft: 8750,
    address: "Iscon Elegance, Satellite",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380015",
    lat: 23.0350,
    lng: 72.5150,
    area: 1600,
    bedrooms: 3,
    bathrooms: 3,
    yearBuilt: 2019,
    parking: 2,
    floors: 8,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80",
    ],
    amenities: ["Modular Kitchen", "Covered Parking", "Gym", "Clubhouse", "24hr Security"],
    views: 1956,
    agentIndex: 0,
  },
  {
    title: "4BHK Row House — Thaltej",
    description: "Elegant row house with private garden and terrace in a secured gated township in Thaltej. Features a double-height entrance lobby, dedicated servant quarters, and German kitchen fittings.",
    type: "residential",
    subtype: "Row House",
    status: "for_sale",
    price: 32000000, // ₹3.2 Cr
    pricePerSqft: 10000,
    address: "Thaltej Meadows, Thaltej",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380059",
    lat: 23.0600,
    lng: 72.5060,
    area: 3200,
    bedrooms: 4,
    bathrooms: 4,
    yearBuilt: 2021,
    parking: 2,
    floors: 2,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=1200&q=80",
      "https://images.unsplash.com/photo-1599427303058-f04cbcf4756f?w=1200&q=80",
    ],
    amenities: ["Private Garden", "Servant Quarters", "Swimming Pool", "Clubhouse", "German Kitchen", "Solar Panels"],
    views: 3120,
    agentIndex: 3,
  },
  {
    title: "2BHK Rental Apartment — Navrangpura",
    description: "Fully furnished 2BHK apartment on offer for rent in prime Navrangpura near Ellis Bridge. Steps from CG Road restaurants and shopping. Ideal for professionals and young couples.",
    type: "residential",
    subtype: "Apartment",
    status: "for_rent",
    price: 28000, // ₹28,000/mo
    pricePerSqft: null,
    address: "Nav Arcade, Navrangpura",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380009",
    lat: 23.0384,
    lng: 72.5582,
    area: 1050,
    bedrooms: 2,
    bathrooms: 2,
    yearBuilt: 2018,
    parking: 1,
    floors: 5,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80",
    ],
    amenities: ["Fully Furnished", "AC", "WiFi Ready", "Covered Parking", "Lift"],
    views: 1834,
    agentIndex: 5,
  },
  {
    title: "3BHK Rent — SG Highway Facing Apartment",
    description: "Spacious 3BHK on the 10th floor with SG Highway views. Semi-furnished with wardrobes and modular kitchen. Easy access to Prahladnagar Garden and major IT parks.",
    type: "residential",
    subtype: "Apartment",
    status: "for_rent",
    price: 45000, // ₹45,000/mo
    pricePerSqft: null,
    address: "Sky One, SG Highway",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380054",
    lat: 23.0300,
    lng: 72.5000,
    area: 1650,
    bedrooms: 3,
    bathrooms: 3,
    yearBuilt: 2020,
    parking: 2,
    floors: 10,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1560185127-6a97b9e66fba?w=1200&q=80",
    ],
    amenities: ["SG Highway View", "Modular Kitchen", "Swimming Pool", "Gym", "Visitor Parking"],
    views: 2234,
    agentIndex: 1,
  },
  {
    title: "1BHK Studio — Ambawadi",
    description: "Compact and smart 1BHK studio perfectly suited for students and working professionals near Ambawadi Circle. Fully furnished with all utilities, 10 min from Law Garden.",
    type: "residential",
    subtype: "Studio",
    status: "for_rent",
    price: 15000, // ₹15,000/mo
    pricePerSqft: null,
    address: "Ambawadi Circle, Ambawadi",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380006",
    lat: 23.0280,
    lng: 72.5617,
    area: 560,
    bedrooms: 1,
    bathrooms: 1,
    yearBuilt: 2017,
    parking: 1,
    floors: 3,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80",
    ],
    amenities: ["Fully Furnished", "Wi-Fi", "Air Conditioning", "Water Purifier"],
    views: 1520,
    agentIndex: 1,
  },
  {
    title: "5BHK Bungalow — Judges Bungalow Road",
    description: "Grand independent bungalow on 500 sq yd plot in the most prestigious address in Ahmedabad. Italian marble floors, home theatre, temperature-controlled wine cellar, and a private pool.",
    type: "residential",
    subtype: "Bungalow",
    status: "for_sale",
    price: 120000000, // ₹12 Cr
    pricePerSqft: 16000,
    address: "5, Judges Bungalow Road",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380054",
    lat: 23.0520,
    lng: 72.5080,
    area: 7500,
    bedrooms: 5,
    bathrooms: 6,
    yearBuilt: 2019,
    parking: 4,
    floors: 3,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80",
    ],
    amenities: ["Private Pool", "Home Theatre", "Wine Cellar", "Modular Kitchen", "Solar Power", "Servants Quarters", "Terrace Garden"],
    views: 6104,
    agentIndex: 3,
  },
  {
    title: "2BHK New Apartment — Chandkheda",
    description: "New 2BHK in an upcoming township near Chandkheda Metro Station. Vastu-compliant design, modular kitchen, and landscaped garden. Excellent connectivity to Gandhinagar.",
    type: "residential",
    subtype: "Apartment",
    status: "for_sale",
    price: 5200000, // ₹52 L
    pricePerSqft: 4500,
    address: "Akshar Green, Chandkheda",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "382424",
    lat: 23.1100,
    lng: 72.5950,
    area: 1155,
    bedrooms: 2,
    bathrooms: 2,
    yearBuilt: 2023,
    parking: 1,
    floors: 7,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa12c98?w=1200&q=80",
    ],
    amenities: ["Metro Connectivity", "Modular Kitchen", "24hr Security", "Water Harvesting", "Solar Panels"],
    views: 1245,
    agentIndex: 1,
  },
  {
    title: "3BHK Apartment — Gota",
    description: "Affordable 3BHK in a vibrant neighbourhood in Gota with excellent schools and malls nearby. Vaastu-compliant, good natural light, and a large balcony with garden view.",
    type: "residential",
    subtype: "Apartment",
    status: "for_sale",
    price: 8200000, // ₹82 L
    pricePerSqft: 5500,
    address: "Siddhivinayak Greens, Gota",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "382481",
    lat: 23.0950,
    lng: 72.5600,
    area: 1491,
    bedrooms: 3,
    bathrooms: 2,
    yearBuilt: 2021,
    parking: 1,
    floors: 9,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80",
    ],
    amenities: ["Large Balcony", "Swimming Pool", "Jogging Track", "Kids Area", "Covered Parking"],
    views: 1788,
    agentIndex: 1,
  },
  {
    title: "4BHK Duplex Villa — Science City Road",
    description: "Architecturally designed duplex villa in a premium township on Science City Road. Open-plan living, floating staircase, private terrace, and smart home integration for lighting, AC and security.",
    type: "residential",
    subtype: "Duplex",
    status: "for_sale",
    price: 28000000, // ₹2.8 Cr
    pricePerSqft: 9800,
    address: "Greenwood Township, Science City Road",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380060",
    lat: 23.0420,
    lng: 72.5420,
    area: 2857,
    bedrooms: 4,
    bathrooms: 4,
    yearBuilt: 2022,
    parking: 2,
    floors: 2,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80",
    ],
    amenities: ["Smart Home", "Private Terrace", "Clubhouse", "Swimming Pool", "EV Charging", "Solar Power"],
    views: 3340,
    agentIndex: 0,
  },
  {
    title: "2BHK Apartment — Maninagar",
    description: "Well-maintained 2BHK in the established neighbourhood of Maninagar, close to Maninagar Railway Station. Tiled floors, RCC construction, and good ventilation.",
    type: "residential",
    subtype: "Apartment",
    status: "for_sale",
    price: 4200000, // ₹42 L
    pricePerSqft: 4200,
    address: "Ashirwad Flats, Maninagar",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380008",
    lat: 22.9945,
    lng: 72.6010,
    area: 1000,
    bedrooms: 2,
    bathrooms: 2,
    yearBuilt: 2016,
    parking: 1,
    floors: 4,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80",
    ],
    amenities: ["Covered Parking", "Lift", "24hr Water Supply", "Near Railway Station"],
    views: 1320,
    agentIndex: 5,
  },
  {
    title: "3BHK Furnished Flat for Rent — Paldi",
    description: "Fully furnished 3BHK near Gujarat University and Physical Research Laboratory. Ideal for faculty, researchers and ISRO employees. Includes all appliances, excellent public transport.",
    type: "residential",
    subtype: "Apartment",
    status: "for_rent",
    price: 35000, // ₹35,000/mo
    pricePerSqft: null,
    address: "University Road, Paldi",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380007",
    lat: 23.0178,
    lng: 72.5612,
    area: 1400,
    bedrooms: 3,
    bathrooms: 2,
    yearBuilt: 2018,
    parking: 1,
    floors: 4,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80",
    ],
    amenities: ["Fully Furnished", "Near University", "Public Transport", "Wi-Fi Ready", "Lift"],
    views: 2021,
    agentIndex: 1,
  },
  // ─── COMMERCIAL ───────────────────────────────────────────────────────────
  {
    title: "Grade-A Office Space — GIFT City",
    description: "Premium furnished office space in GIFT City, India's first IFSC. Ideal for fintech firms, banks, and global corporations. 24×7 power backup, fibre internet, and international-grade fire safety systems.",
    type: "commercial",
    subtype: "Office",
    status: "for_sale",
    price: 55000000, // ₹5.5 Cr
    pricePerSqft: 14000,
    address: "GIFT Tower 3, GIFT City",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "382355",
    lat: 23.1620,
    lng: 72.6730,
    area: 3929,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2022,
    parking: 10,
    floors: 18,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80",
      "https://images.unsplash.com/photo-1497366412874-3415097a27ba?w=1200&q=80",
    ],
    amenities: ["24hr Power Backup", "Fibre Internet", "Fire Safety", "Conference Rooms", "Cafeteria", "CCTV", "Reserved Parking"],
    views: 4512,
    agentIndex: 2,
  },
  {
    title: "Showroom Space — CG Road",
    description: "Prime 3,500 sq ft showroom on the most coveted commercial stretch of Ahmedabad — CG Road. Ground-floor frontage with massive glass facade, high footfall, and basement parking for 20 vehicles.",
    type: "commercial",
    subtype: "Showroom",
    status: "for_sale",
    price: 42000000, // ₹4.2 Cr
    pricePerSqft: 12000,
    address: "CG Road, Navrangpura",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380009",
    lat: 23.0375,
    lng: 72.5600,
    area: 3500,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2015,
    parking: 20,
    floors: 1,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&q=80",
      "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80",
    ],
    amenities: ["Ground Floor", "Glass Facade", "High Footfall", "Basement Parking", "DG Backup"],
    views: 3920,
    agentIndex: 2,
  },
  {
    title: "IT/ITES Office — SG Highway Tech Park",
    description: "Ready-to-move furnished IT office with 80-seat capacity in a tech park on SG Highway. Includes reception, server room, 8 cabins, and a large open-plan floor. Near Iscon Mega Mall.",
    type: "commercial",
    subtype: "Office",
    status: "for_rent",
    price: 180000, // ₹1.8L/mo
    pricePerSqft: null,
    address: "Navkar Business Park, SG Highway",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380054",
    lat: 23.0280,
    lng: 72.5060,
    area: 4000,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2020,
    parking: 15,
    floors: 5,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1497366412874-3415097a27ba?w=1200&q=80",
    ],
    amenities: ["80-Seat Capacity", "Server Room", "Reception", "DG Backup", "CCTV", "Cafeteria Access"],
    views: 2812,
    agentIndex: 2,
  },
  {
    title: "Retail Shop — Ozone Mall, Vastrapur",
    description: "Lease a prime retail unit on the ground floor of a high-footfall mall near Vastrapur Lake. Suitable for fashion, electronics, F&B or lifestyle brands. Assured footfall of 15,000+ daily visitors.",
    type: "commercial",
    subtype: "Retail",
    status: "for_rent",
    price: 120000, // ₹1.2L/mo
    pricePerSqft: null,
    address: "Ozone Mall, Vastrapur",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380015",
    lat: 23.0390,
    lng: 72.5295,
    area: 1200,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2018,
    parking: 5,
    floors: 1,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&q=80",
    ],
    amenities: ["High Footfall", "Ground Floor", "HVAC", "Brand Signage Rights", "Common Area Maintenance"],
    views: 3188,
    agentIndex: 2,
  },
  {
    title: "Hotel Investment Property — Sardar Patel Ring Road",
    description: "Operating budget hotel with 42 rooms and 80% occupancy near the new Ring Road interchange. Strong cash flow asset — ideal as-is or for brand conversion. CRISIL-rated investment grade.",
    type: "commercial",
    subtype: "Hotel",
    status: "for_sale",
    price: 180000000, // ₹18 Cr
    pricePerSqft: 11000,
    address: "Ring Road Interchange, Sarkhej",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "382210",
    lat: 22.9810,
    lng: 72.4910,
    area: 16364,
    bedrooms: 42,
    bathrooms: 42,
    yearBuilt: 2017,
    parking: 30,
    floors: 5,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&q=80",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&q=80",
    ],
    amenities: ["42 Rooms", "Restaurant", "Conference Room", "Swimming Pool", "Gym", "Parking for 30", "Reception Desk"],
    views: 5621,
    agentIndex: 5,
  },
  {
    title: "Restaurant & Banquet Space — Law Garden",
    description: "Licensed restaurant premises with full kitchen, 120-cover dining area, and a detachable 200-person banquet hall. Iconic Law Garden location — one of the most visited evening hubs in Ahmedabad.",
    type: "commercial",
    subtype: "Restaurant",
    status: "for_rent",
    price: 200000, // ₹2L/mo
    pricePerSqft: null,
    address: "Law Garden, Ellisbridge",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380006",
    lat: 23.0300,
    lng: 72.5580,
    area: 5000,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2014,
    parking: 20,
    floors: 2,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&q=80",
    ],
    amenities: ["Kitchen Setup", "120-Cover Dining", "200-Person Banquet", "Bar Counter", "AV System", "Outdoor Seating"],
    views: 4210,
    agentIndex: 2,
  },
  {
    title: "Office Space — Prahladnagar Corporate Road",
    description: "1,800 sq ft furnished office on the bustling Prahladnagar Corporate Road. Plug-and-play setup with dedicated internet, breakout area, and meeting room. Popular with startups and SMEs.",
    type: "commercial",
    subtype: "Office",
    status: "for_rent",
    price: 85000, // ₹85,000/mo
    pricePerSqft: null,
    address: "Iscon Business Hub, Prahlad Nagar",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380015",
    lat: 23.0240,
    lng: 72.5090,
    area: 1800,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2019,
    parking: 6,
    floors: 7,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1497366412874-3415097a27ba?w=1200&q=80",
    ],
    amenities: ["Plug & Play", "Meeting Room", "Breakout Area", "Dedicated Internet", "AC", "Security"],
    views: 2555,
    agentIndex: 2,
  },
  {
    title: "Cold Storage Facility — Narol",
    description: "FSSAI-licensed cold storage facility with 5,000-tonne capacity near Narol Industrial Area. Multi-temperature zones for produce, dairy and pharmaceuticals. NH-48 frontage.",
    type: "commercial",
    subtype: "Cold Storage",
    status: "for_sale",
    price: 85000000, // ₹8.5 Cr
    pricePerSqft: 4500,
    address: "GIDC Narol, Phase 2",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "382405",
    lat: 22.9650,
    lng: 72.6350,
    area: 18889,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2018,
    parking: 20,
    floors: 1,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1200&q=80",
    ],
    amenities: ["5,000 Tonne Capacity", "Multi-Temperature Zones", "FSSAI Licensed", "NH-48 Frontage", "24hr Power Backup"],
    views: 1980,
    agentIndex: 4,
  },
  // ─── PLOTS ────────────────────────────────────────────────────────────────
  {
    title: "Residential Plot — Bopal-Ambli Road",
    description: "Prime 300 sq yd residential plot on Bopal-Ambli Road in a AUDA-approved layout. Clear title, no encumbrances, and surrounded by premium residential projects. Ready for immediate construction.",
    type: "plot",
    subtype: "Residential Plot",
    status: "for_sale",
    price: 9500000, // ₹95 L
    pricePerSqft: 3167,
    address: "Bopal-Ambli Road",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380058",
    lat: 23.0120,
    lng: 72.4840,
    area: 2700,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: null,
    parking: null,
    floors: null,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80",
    ],
    amenities: ["AUDA Approved", "Clear Title", "Corner Plot", "Ready to Build", "Electricity & Water Connection"],
    views: 1620,
    agentIndex: 4,
  },
  {
    title: "Commercial Plot — SP Ring Road",
    description: "1,000 sq yd commercial plot with excellent SP Ring Road frontage. Suitable for hotel, hospital, commercial complex or petrol station. AUDA NA permission in process.",
    type: "plot",
    subtype: "Commercial Plot",
    status: "for_sale",
    price: 35000000, // ₹3.5 Cr
    pricePerSqft: 3889,
    address: "SP Ring Road, Sanand Cross",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "382213",
    lat: 22.9700,
    lng: 72.4780,
    area: 9000,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: null,
    parking: null,
    floors: null,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80",
    ],
    amenities: ["Ring Road Frontage", "High Visibility", "NA Permission In Process", "Wide Road Access"],
    views: 2840,
    agentIndex: 4,
  },
  {
    title: "Farmhouse Land — Shilaj-Rancharda Road",
    description: "4-acre agricultural land with farmhouse potential on the serene Shilaj-Rancharda stretch. Borewell, electricity line, and 30-ft road frontage. Scenic open views — ideal weekend getaway development.",
    type: "plot",
    subtype: "Agricultural / Farmhouse",
    status: "for_sale",
    price: 28000000, // ₹2.8 Cr
    pricePerSqft: 1612,
    address: "Rancharda Village, Shilaj Road",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "382481",
    lat: 23.0600,
    lng: 72.4640,
    area: 174240,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: null,
    parking: null,
    floors: null,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80",
    ],
    amenities: ["Borewell", "Electricity Connection", "30-ft Road Frontage", "Open Scenic Views", "Farmhouse Development Permitted"],
    views: 1980,
    agentIndex: 4,
  },
  {
    title: "NA Residential Plot — Gota",
    description: "170 sq yd NA plot in a brand-new AUDA-approved layout in Gota. Excellent connectivity to SG Highway and upcoming Metro station. All utilities at plot boundary.",
    type: "plot",
    subtype: "Residential Plot",
    status: "for_sale",
    price: 5100000, // ₹51 L
    pricePerSqft: 3353,
    address: "New Layout, Gota",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "382481",
    lat: 23.0880,
    lng: 72.5600,
    area: 1530,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: null,
    parking: null,
    floors: null,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80",
    ],
    amenities: ["NA Done", "AUDA Approved", "Water Connection", "Electricity Nearby", "Paved Road"],
    views: 1155,
    agentIndex: 4,
  },
  {
    title: "Investment Plot — New Ranip Metro Zone",
    description: "250 sq yd plot within 500m of the upcoming New Ranip Metro Station. High appreciation potential driven by Metro Phase-2 construction. AUDA approved, clear title.",
    type: "plot",
    subtype: "Investment Plot",
    status: "for_sale",
    price: 7500000, // ₹75 L
    pricePerSqft: 3333,
    address: "New Ranip, Near Metro Station",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "382480",
    lat: 23.0780,
    lng: 72.5730,
    area: 2250,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: null,
    parking: null,
    floors: null,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80",
    ],
    amenities: ["Metro Zone", "AUDA Approved", "High Appreciation", "Near Infrastructure", "Clear Title"],
    views: 2890,
    agentIndex: 5,
  },
  {
    title: "Corner Plot — Motera Stadium Area",
    description: "Rare 300 sq yd corner plot in the booming Motera area near the world's largest cricket stadium. Surrounded by new residential projects, hotel chains, and retail development.",
    type: "plot",
    subtype: "Commercial Plot",
    status: "for_sale",
    price: 13500000, // ₹1.35 Cr
    pricePerSqft: 5000,
    address: "Motera, Near Narendra Modi Stadium",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380005",
    lat: 23.0900,
    lng: 72.6000,
    area: 2700,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: null,
    parking: null,
    floors: null,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80",
    ],
    amenities: ["Corner Plot", "Near Stadium", "High Visibility", "Commercial Potential"],
    views: 2310,
    agentIndex: 5,
  },
  // ─── INDUSTRIAL ───────────────────────────────────────────────────────────
  {
    title: "Industrial Shed — GIDC Vatva Phase 3",
    description: "10,000 sq ft pre-engineered steel industrial shed in GIDC Vatva Phase 3. 24-ft clear height, 1 MVA power supply, EOT crane provision, and direct highway access. Ideal for manufacturing and assembly.",
    type: "industrial",
    subtype: "Industrial Shed",
    status: "for_sale",
    price: 55000000, // ₹5.5 Cr
    pricePerSqft: 5500,
    address: "GIDC Vatva Phase 3, Vatva",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "382445",
    lat: 22.9600,
    lng: 72.6420,
    area: 10000,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2020,
    parking: 15,
    floors: 1,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1565715891038-3fa6fed2c6b1?w=1200&q=80",
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&q=80",
    ],
    amenities: ["24-ft Clear Height", "1 MVA Power", "EOT Crane Provision", "Highway Access", "Water & Drainage", "Admin Block"],
    views: 2950,
    agentIndex: 4,
  },
  {
    title: "Warehouse & Logistics Hub — Changodar GIDC",
    description: "Modern 25,000 sq ft logistics warehouse near NH-48 in Changodar. 10 docking bays, sprinkler system, FM2 flooring, and solar rooftop. Ideal for e-commerce and 3PL operators.",
    type: "industrial",
    subtype: "Warehouse",
    status: "for_sale",
    price: 130000000, // ₹13 Cr
    pricePerSqft: 5200,
    address: "Changodar GIDC, Sanand",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "382213",
    lat: 22.9540,
    lng: 72.4600,
    area: 25000,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2021,
    parking: 30,
    floors: 1,
    featured: true,
    images: [
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&q=80",
      "https://images.unsplash.com/photo-1565715891038-3fa6fed2c6b1?w=1200&q=80",
    ],
    amenities: ["10 Docking Bays", "FM2 Flooring", "Solar Rooftop", "Sprinkler System", "NH-48 Access", "Security Cabin"],
    views: 3820,
    agentIndex: 4,
  },
  {
    title: "Industrial Land — Naroda GIDC",
    description: "6,000 sq yd industrial plot in Naroda GIDC with NA and industrial conversion done. Three-phase power available, wide internal roads, and 50-ft highway frontage. Suitable for SME manufacturing unit.",
    type: "industrial",
    subtype: "Industrial Plot",
    status: "for_sale",
    price: 42000000, // ₹4.2 Cr
    pricePerSqft: 1556,
    address: "Naroda GIDC, Naroda",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "382330",
    lat: 23.0800,
    lng: 72.6580,
    area: 54000,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: null,
    parking: null,
    floors: null,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1565715891038-3fa6fed2c6b1?w=1200&q=80",
    ],
    amenities: ["NA Done", "3-Phase Power", "50-ft Frontage", "Wide Internal Roads", "GIDC Infrastructure"],
    views: 1748,
    agentIndex: 4,
  },
  {
    title: "Light-Engineering Factory — Odhav",
    description: "4,500 sq ft light engineering factory operational since 2012. Includes 200 sq ft admin office, single-phase and 3-phase electrical supply, overhead crane, and drainage. Ideal for auto ancillary and precision parts.",
    type: "industrial",
    subtype: "Factory",
    status: "for_sale",
    price: 28000000, // ₹2.8 Cr
    pricePerSqft: 6222,
    address: "Odhav Ring Road, Odhav",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "382415",
    lat: 23.0200,
    lng: 72.6620,
    area: 4500,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2012,
    parking: 8,
    floors: 1,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1565715891038-3fa6fed2c6b1?w=1200&q=80",
    ],
    amenities: ["Overhead Crane", "3-Phase Supply", "Admin Office", "Drainage", "Security Fence"],
    views: 1540,
    agentIndex: 4,
  },
  {
    title: "Industrial Shed for Rent — GIDC Kathwada",
    description: "5,000 sq ft industrial shed on rent in GIDC Kathwada, 10 minutes from Sardar Patel Ring Road. 20-ft clear height, DG backup, and toilet/canteen facilities available. Suitable for pharma and food processing.",
    type: "industrial",
    subtype: "Industrial Shed",
    status: "for_rent",
    price: 150000, // ₹1.5L/mo
    pricePerSqft: null,
    address: "GIDC Kathwada, Kathwada",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "382430",
    lat: 23.0050,
    lng: 72.6800,
    area: 5000,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2016,
    parking: 10,
    floors: 1,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&q=80",
    ],
    amenities: ["20-ft Clear Height", "DG Backup", "Canteen", "Security", "Ring Road Access"],
    views: 1290,
    agentIndex: 4,
  },
  // Additional residential
  {
    title: "3BHK Premium — Vejalpur",
    description: "Newly built 3BHK in a premium gated society in Vejalpur, 10 min from APMC market and Sarkhej highway. Wide roads, green landscaping, children's park, and gymnasium.",
    type: "residential",
    subtype: "Apartment",
    status: "for_sale",
    price: 9800000, // ₹98 L
    pricePerSqft: 5750,
    address: "Maple Grove, Vejalpur",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380051",
    lat: 23.0030,
    lng: 72.5240,
    area: 1704,
    bedrooms: 3,
    bathrooms: 3,
    yearBuilt: 2023,
    parking: 2,
    floors: 11,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80",
    ],
    amenities: ["Gymnasium", "Landscaped Garden", "Children Park", "Swimming Pool", "Visitor Parking"],
    views: 1680,
    agentIndex: 1,
  },
  {
    title: "3BHK Flat — Shyamal Cross Road",
    description: "Bright, airy 3BHK on the 7th floor with cross-ventilation and city views. Walking distance from Shyamal Cross Road micro-market, metro station, and school clusters.",
    type: "residential",
    subtype: "Apartment",
    status: "for_sale",
    price: 11500000, // ₹1.15 Cr
    pricePerSqft: 6389,
    address: "Saffron Towers, Shyamal",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380015",
    lat: 23.0200,
    lng: 72.5420,
    area: 1800,
    bedrooms: 3,
    bathrooms: 3,
    yearBuilt: 2020,
    parking: 1,
    floors: 7,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=1200&q=80",
    ],
    amenities: ["Cross Ventilation", "Near Metro", "Children Play Area", "Clubhouse", "DG Backup"],
    views: 1444,
    agentIndex: 0,
  },
  {
    title: "2BHK Sold — Nikol",
    description: "Sold listing: 2BHK apartment in Nikol, located close to Vastral Metro Station. Good value for money proposition in the rapidly developing eastern corridor.",
    type: "residential",
    subtype: "Apartment",
    status: "sold",
    price: 3800000, // ₹38 L
    pricePerSqft: 3800,
    address: "Shree Residency, Nikol",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "382350",
    lat: 23.0350,
    lng: 72.6520,
    area: 1000,
    bedrooms: 2,
    bathrooms: 2,
    yearBuilt: 2018,
    parking: 1,
    floors: 4,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80",
    ],
    amenities: ["Near Metro", "Society Garden", "Visitor Parking"],
    views: 980,
    agentIndex: 5,
  },
  // Additional commercial
  {
    title: "Medical Office / Clinic Space — Satellite",
    description: "1,200 sq ft clinic or medical office space on the ground floor in Satellite. Ideal for a diagnostic centre, dental clinic, or paediatric practice. Separate entrance, RO water, and generator backup.",
    type: "commercial",
    subtype: "Medical / Clinic",
    status: "for_rent",
    price: 65000, // ₹65,000/mo
    pricePerSqft: null,
    address: "Yash Complex, Satellite Road",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380015",
    lat: 23.0370,
    lng: 72.5180,
    area: 1200,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2016,
    parking: 4,
    floors: 1,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1497366412874-3415097a27ba?w=1200&q=80",
    ],
    amenities: ["Separate Entrance", "Generator Backup", "RO Water", "Disabled Access", "AC"],
    views: 1870,
    agentIndex: 2,
  },
  // Additional plots
  {
    title: "NA Plot — Sindhu Bhavan Road",
    description: "Premium 200 sq yd NA plot on Sindhu Bhavan Road, one of the fastest appreciating micro-markets in East Ahmedabad. AUDA approved, all utilities connected, near IIM-A and residential townships.",
    type: "plot",
    subtype: "Residential Plot",
    status: "for_sale",
    price: 12000000, // ₹1.2 Cr
    pricePerSqft: 6667,
    address: "Sindhu Bhavan Road, Bodakdev",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380054",
    lat: 23.0560,
    lng: 72.5200,
    area: 1800,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: null,
    parking: null,
    floors: null,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80",
    ],
    amenities: ["NA Done", "AUDA Approved", "Utilities Connected", "Near IIM-A", "Prime Location"],
    views: 3120,
    agentIndex: 5,
  },
  // sold commercial
  {
    title: "Office Space Sold — Ahmedabad One Mall",
    description: "Sold: 2,400 sq ft office unit in Ahmedabad One, a landmark commercial destination on the Eastern Expressway. Strong capital appreciation since purchase in 2018.",
    type: "commercial",
    subtype: "Office",
    status: "sold",
    price: 28000000, // ₹2.8 Cr
    pricePerSqft: 11667,
    address: "Ahmedabad One Mall, Vastrapur",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380015",
    lat: 23.0400,
    lng: 72.5280,
    area: 2400,
    bedrooms: null,
    bathrooms: null,
    yearBuilt: 2018,
    parking: 4,
    floors: 10,
    featured: false,
    images: [
      "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80",
    ],
    amenities: ["Prime Location", "Mall Connectivity", "Conference Room", "Food Court Access"],
    views: 2240,
    agentIndex: 2,
  },
];

async function seed() {
  console.log("Clearing existing data...");
  await db.delete(propertiesTable);
  await db.delete(agentsTable);

  console.log("Seeding Ahmedabad agents...");
  const insertedAgents = await db.insert(agentsTable).values(agents).returning({ id: agentsTable.id });
  console.log(`Inserted ${insertedAgents.length} agents`);

  console.log(`Inserting ${properties.length} Ahmedabad properties...`);
  const propsWithAgents = properties.map((p) => ({
    ...p,
    agentId: insertedAgents[p.agentIndex % insertedAgents.length].id,
  }));

  // Strip agentIndex from each property
  const cleanProps = propsWithAgents.map(({ agentIndex: _a, ...rest }) => rest);

  await db.insert(propertiesTable).values(cleanProps as any);
  console.log(`Inserted ${properties.length} Ahmedabad properties`);
  console.log("Seed complete! 🇮🇳");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
